[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.15.11"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-containerregistry"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "v1.1"

[prune]
  go-tests = true
  unused-packages = true
