[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.20.8"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-containerregistry"

[[constraint]]
  name = "github.com/robfig/cron"
  version = "v1.2.0"

[prune]
  go-tests = true
  unused-packages = true
